# Lecture 7: Data Handling and Analysis in Python 

data is usually multi-dimensional
- fMRI = voxels x time
- EEG = electrodes x time
- questionnaires: subjects x responses

Tuples are unchangeable 

In [1]:
coords = [(1,1), (1,2), (1,3)]

In [2]:
type(coords)

list

In [4]:
type(coords[0])

tuple

- dictionaries allow you to store key-value pairs 
- declared with curly brackets


In [5]:
nbaTeams = {'Los Angeles':'lakers', 'Toronto':'Raptors', 'Miami':"Heat"}

- retrieve a dictionary item by Key:
- nbaTeams["toronto"]
- nbaTeams.get["toronto"]
  

In [6]:
nbaTeams['Toronto']

'Raptors'

In [9]:
nbaTeams.get['Toronto']

TypeError: 'builtin_function_or_method' object is not subscriptable

## Numpy

- import numpy as np
- have to call the method 

## Numpy Arrays

In [74]:
import numpy as np
arr = np.array([1,2,3,4,5])

In [12]:
mdArr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [13]:
print(mdArr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
threed = np.array([[[0,0,0], [0,0,0]], [[1,1,1], [1,1,1]]])

In [16]:
print(threed)

[[[0 0 0]
  [0 0 0]]

 [[1 1 1]
  [1 1 1]]]


In [17]:
arr[0]

np.int64(1)

In [18]:
mdArr[0]

array([1, 2, 3])

In [20]:
mdArr[0,0]

np.int64(1)

In [22]:
for x in mdArr:
    print(x)

[1 2 3]
[4 5 6]
[7 8 9]


In [23]:
for x in mdArr:
    #print(x)
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9


the first loop goes through the 3 triplets. The second loop goes through each value within the triplets

## other methods

can reshape an array using arr.reshape, can stack arrays on top of each other changing the dimension via np.vsstack, .array_split splits an exisiting 1D array into three separate parts

## Indexing and Masking 

In [26]:
newArr = np.array([5, 6, 2, 4, 7, 8, 2, 1, 0])

In [27]:
Mask = newArr > 2

In [30]:
print(Mask)

[ True  True False  True  True  True False False False]


In [31]:
newArr[Mask]

array([5, 6, 4, 7, 8])

return the values at that index that is true

In [32]:
cleanData = newArr[Mask]

In [ ]:
cleanData = newArr[newArr > 2]

In [33]:
print(cleanData)

[5 6 4 7 8]


In [34]:
newArr2 = np.array([0,1,2,3,4,5,6,7,8])

In [35]:
x = newArr[newArr2 > 4]

In [36]:
print(x)

[8 2 1 0]


## Other ways of indexing 

In [ ]:
np.nonzero(a) # returns all the non-zero elements 
np.where(condition, [x,y], /) returns elements from x or y depending on condition 

## Numpy

In [38]:
data = np.loadtxt(fname='inflammation-01.csv', delimiter =',')

In [39]:
print(data.shape)

(60, 40)


In [40]:
data[10,35]

np.float64(3.0)

In [41]:
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [42]:
data[0,:]

array([ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
        5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
        4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
        0.])

In [43]:
data[0:1, 0:1]

array([[0.]])

## Statistics using Numpy

In [44]:
meanval, maxval, minval, stdval = np.mean(data), np.amax(data), np.amin(data), np.std(data)

In [45]:
print(meanval)

6.14875


In [46]:
meanval = np.mean(data, 0)

In [47]:
print(meanval)

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]


In [ ]:
meanval = np.mean(data[0], 0)

In [48]:
np.mean(data[0, :])

np.float64(5.45)

In [49]:
np.mean(data[:,0])

np.float64(0.0)

## Numpy Random

In [75]:
from numpy import random 

In [51]:
random.randint(100) # generates a random integer from 0 to 100 

83

In [76]:
randData = random.randint(5,10, size = [10,50])

In [77]:
print(randData)

TypeError: 'numpy.ndarray' object is not callable

In [61]:
random.choice(data[0, :])

np.float64(7.0)

In [62]:
conds = [0, 1, 2]

In [63]:
random.shuffle(conds)

In [67]:
print(conds)

TypeError: 'numpy.ndarray' object is not callable